#!/usr/bin/env bash
set -euo pipefail

# create-pr.sh
# Checks for uncommitted changes, creates a branch, commits, pushes,
# and opens a Pull Request via the GitHub CLI (gh).

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEMO_APP_DIR="${PROJECT_ROOT}/demo-app"

echo "[create-pr] Starting PR creation..."

# ── 1. Git sanity checks ─────────────────────────────────────────────

if ! command -v git &>/dev/null; then
  echo "[create-pr] ERROR: git is not installed."
  exit 1
fi

if ! command -v gh &>/dev/null; then
  echo "[create-pr] ERROR: GitHub CLI (gh) is not installed."
  exit 1
fi

# ── 2. Check for changes ─────────────────────────────────────────────

if git -C "${PROJECT_ROOT}" diff --quiet && git -C "${PROJECT_ROOT}" diff --cached --quiet; then
  echo "[create-pr] No uncommitted changes found. Nothing to PR."
  exit 0
fi

# ── 3. Gather metadata ───────────────────────────────────────────────

BRANCH_NAME="kimchi-auto-fix-$(date +%s)"
COMMIT_MESSAGE="[Kimchi Auto-Fix] Resolve failing CI pipeline

This commit contains an automated fix generated by Kimchi Ferment.
The agent analyzed the test failure, identified the root cause,
and applied the minimal code change necessary to make the tests pass."

# Build the list of changed files for the PR body.
# Capture the current base branch BEFORE creating a new branch.
BASE_BRANCH="$(git -C "${PROJECT_ROOT}" branch --show-current)"

CHANGED_FILES="$(git -C "${PROJECT_ROOT}" diff --name-only HEAD || true)"
if [[ -z "${CHANGED_FILES}" ]]; then
  CHANGED_FILES="$(git -C "${PROJECT_ROOT}" diff --name-only || true)"
fi

# Build validation info.
VALIDATION_INFO=""
if [[ -d "${DEMO_APP_DIR}" ]]; then
  VALIDATION_INFO="Tests were re-run in demo-app after the fix was applied."
else
  VALIDATION_INFO="Validation step skipped (demo-app directory not found)."
fi

# ── 4. Create branch and commit ──────────────────────────────────────

# Ensure git identity is configured (required in CI environments).
GIT_AUTHOR_NAME="$(git -C "${PROJECT_ROOT}" config user.name 2>/dev/null || true)"
GIT_AUTHOR_EMAIL="$(git -C "${PROJECT_ROOT}" config user.email 2>/dev/null || true)"
if [[ -z "${GIT_AUTHOR_NAME}" ]]; then
  git -C "${PROJECT_ROOT}" config user.name "${GITHUB_ACTOR:-Kimchi Auto-Fix}"
fi
if [[ -z "${GIT_AUTHOR_EMAIL}" ]]; then
  git -C "${PROJECT_ROOT}" config user.email "${GITHUB_ACTOR:-kimchi}@users.noreply.github.com"
fi

echo "[create-pr] Creating branch ${BRANCH_NAME}..."
git -C "${PROJECT_ROOT}" checkout -b "${BRANCH_NAME}"

echo "[create-pr] Staging changes..."
git -C "${PROJECT_ROOT}" add -A

echo "[create-pr] Committing changes..."
git -C "${PROJECT_ROOT}" commit -m "${COMMIT_MESSAGE}"

# ── 5. Push branch ───────────────────────────────────────────────────

echo "[create-pr] Pushing branch ${BRANCH_NAME}..."
git -C "${PROJECT_ROOT}" push origin "${BRANCH_NAME}"

# ── 6. Open Pull Request ─────────────────────────────────────────────

PR_TITLE="[Kimchi Auto-Fix] Resolve failing CI pipeline"

PR_BODY=$(cat <<EOF
## Summary
An automated fix was generated by Kimchi Ferment after analyzing the failing CI pipeline logs.

## Changes Made
\`\`\`
${CHANGED_FILES}
\`\`\`

## Validation
${VALIDATION_INFO}

## Notes
Generated automatically using Kimchi Ferment.
EOF
)

echo "[create-pr] Creating Pull Request..."
(
  cd "${PROJECT_ROOT}"
  gh pr create \
    --title "${PR_TITLE}" \
    --body "${PR_BODY}" \
    --head "${BRANCH_NAME}" \
    --base "${BASE_BRANCH}"
)

echo "[create-pr] Pull Request created successfully."
exit 0
